### PR TITLE
Allow files to be preprocessed before inclusion.

### PR DESCRIPTION
**Pull request by timoxley**
This builds upon the functionality in #1, adding the ability to run a file's content through a preprocessor before being added to the JSON. My use case I'm building a backend-less website, where the data is simply defined in json, and I'd like to be able to easily include the content of files in non-JSON formats (e.g. markdown) in my json file.

If there's anything you'd like me to do to make these PRs better, let me know.

### CODE REVIEW

**Comment by tj** [comment]
this is cool, i like the intent _but_ I think that maybe we could use regular plugins per file type, one for markdown etc:

``` js
{ "readme": "markdown readme.md" }
```

or hell maybe even have an option:

``` js
.use(markdown({ prefix: false }))

{ "readme": "readme.md" }
```

**Comment by timoxley** [comment]
Fair call. That's a cleaner api. Just detect the filetype and load any plugin registered for it.

**Comment by tj** [comment]
yeah screw the prefix, if they opt-in with `.use(eson.markdown)` then just check the extension, sounds reasonable to me. Im not sure how well npm's optional dependences work, maybe we should use that but there are so many markdown libs out there :s

**Comment by timoxley** [comment]
Perhaps using a more succinct `include` syntax would make it tidier without increasing risk of accidental inclusion.  e.g.

``` js
{ "readme": "<< readme.md" }
```

Also, the reason the processing functions are attached to the include plugin is because they don't really make sense without it. Perhaps a better syntax would be:

``` js
eson.include.extensions.md  = markdown()

eson()
.use(eson.include)
.use(eson.include.markdown)
```

Or simpler:

``` js
eson()
.use(eson.include)
.use(eson.markdown)
```

Or even better:

``` js
eson()
.use(eson.markdown)
```

In this final case the `include` plugin is implicit but it makes sense that only `.md` files can be included.

Most common use case will probably be `.use(eson.json)` anyway.

**Comment by tj** [comment]
why do they need include? it's just a tiny bit of logic, we can duplicate that stuff

**Comment by timoxley** [comment]
Sure, but you'd lose the ability to use globbing to create [arrays of data, or maps of files](https://github.com/timoxley/eson#collect-files-into-a-map-keyed-by-filename). See #1.

**Comment by tj** [comment]
meh that's alright, I dont have any reason to do globbing personally, not sure if others are really using this lib haha would be nice to have some more use-cases

**Comment by timoxley** [comment]
I'm trying to use this to create a static single-page-app site generator, with no db component at all. just create a hierarchy of json files as your 'database', and eson pulls the db together as a single json file. The json/templates/js/css is shipped off to S3 and voila, single-page web app which uses something like http://angryamoeba.co.uk/spahql-announce/ for  clientside 'db'. Basically, eson serves as the tool to build a 'database' up from a folder hierarchy of assets. This is mainly so I don't have to build any UI for the client to create data in the system, they just create json files and put them in a folder. And if I do want to add a UI, all the UI has to do is generate json files.

e.g. Create a product catalogue by simply dumping product information as json files in a `products` folder:

catalogue.json:

``` js
{
  "products": "include [products/*]"
}
```

products/conditioner.json:

``` js
   {
      "sku": "1",
      "name": "Conditioner"
   }
```

products/shampoo.json:

``` js
   {
      "sku": "2",
      "name": "Shampoo",
      "description": "include shampoo.md"
   }
```

products/shampoo.md:

``` coffee
#### Good shampoo, cleans hair
```

catalogue.json after an eson build:

``` js
{
  "products": [
    { "sku": "1",
      "name": "Conditioner"},
    { "sku": "2",
      "name": "Shampoo",
      "description": "<h4>Good shampoo, cleans hair</h4>"}
  ]
}
```

Seems like a good idea to me.

**Comment by tj** [comment]
ahhh I see that makes things a bit clearer for me, very cool, i'd definitely like to avoid a markdown dep ideally, so many out there and some are better than others depending on what you're really doing

**Comment by timoxley** [comment]
Yep, including anything other than json files should be an external module e.g. `eson-markdown`, and its just listed in the readme.

**Comment by timoxley** [comment]
um, bump

**Comment by timoxley** [comment]
actually, too many conflicts to fix to bring this up to date. Closing.

**Pull request closed without merging**
