### PR TITLE
Globbing includes

### PR DESCRIPTION
**Pull request by timoxley**
This got a bit more tricky than anticipated, but it works ok.

3 systems:

``` javascript

// merge all items matching glob
config: "include config/*" 

// collect as map, keyed by filename (note use of '{}' )
config: "include {config/*}"
// e.g.
{
  database: { 
    // db settings from config/database.json 
  },
  app: { 
    // app settings from config/app.json 
  }
}

// collect as an array, (note use of '[]' )
users: "include [users/*]" 
// e.g.
{
  users: [
      {user: 'from users/dave.json'}
      {user: 'from users/barry.json'}
      {user: 'from users/joe.json'}
  ]
}

```

### CODE REVIEW

**Comment by timoxley** [comment]
The readme could probably do with some work, let me know what you think.

**Comment by 3rd-Eden** [comment]
Do want

**Comment by timoxley** [comment]
@visionmedia updated this to work with your latest master. Also refactored the code a bit as previously it looked like the ravings of a madman, high on mapreduce.

**Comment by timoxley** [comment]
bump

**Pull request merged**
